amrutha tallam

importing libraries

In [116]:
import pandas as pd

In [60]:
data=pd.read_csv("C://Users//user//Downloads//dc-wikia-data.csv")

In [61]:
data.head()

page_id                         name                              urlslug  \
0     1422         Batman (Bruce Wayne)         \/wiki\/Batman_(Bruce_Wayne)   
1    23387        Superman (Clark Kent)        \/wiki\/Superman_(Clark_Kent)   
2     1458   Green Lantern (Hal Jordan)   \/wiki\/Green_Lantern_(Hal_Jordan)   
3     1659     James Gordon (New Earth)     \/wiki\/James_Gordon_(New_Earth)   
4     1576  Richard Grayson (New Earth)  \/wiki\/Richard_Grayson_(New_Earth)   

                ID            ALIGN         EYE        HAIR              SEX  \
0  Secret Identity  Good Characters   Blue Eyes  Black Hair  Male Characters   
1  Secret Identity  Good Characters   Blue Eyes  Black Hair  Male Characters   
2  Secret Identity  Good Characters  Brown Eyes  Brown Hair  Male Characters   
3  Public Identity  Good Characters  Brown Eyes  White Hair  Male Characters   
4  Secret Identity  Good Characters   Blue Eyes  Black Hair  Male Characters   

   GSM              ALIVE  APPEARANCES FIRST APPEARANCE    YEAR  
0  NaN  Living Characters       3093.0        1939, May  1939.0  
1  NaN  Living Characters       2496.0    1986, October  1986.0  
2  NaN  Living Characters       1565.0    1959, October  1959.0  
3  NaN  Living Characters       1316.0   1987, February  1987.0  
4  NaN  Living Characters       1237.0      1940, April  1940.0

checking duplicate values

In [62]:
data.duplicated().value_counts()

False    6896
Name: count, dtype: int64

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6896 entries, 0 to 6895
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   page_id           6896 non-null   int64  
 1   name              6896 non-null   object 
 2   urlslug           6896 non-null   object 
 3   ID                4883 non-null   object 
 4   ALIGN             6295 non-null   object 
 5   EYE               3268 non-null   object 
 6   HAIR              4622 non-null   object 
 7   SEX               6771 non-null   object 
 8   GSM               64 non-null     object 
 9   ALIVE             6893 non-null   object 
 10  APPEARANCES       6541 non-null   float64
 11  FIRST APPEARANCE  6827 non-null   object 
 12  YEAR              6827 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 700.5+ KB


In [64]:
data.describe()

page_id  APPEARANCES         YEAR
count    6896.000000  6541.000000  6827.000000
mean   147441.209252    23.625134  1989.766662
std    108388.631149    87.378509    16.824194
min      1380.000000     1.000000  1935.000000
25%     44105.500000     2.000000  1983.000000
50%    141267.000000     6.000000  1992.000000
75%    213203.000000    15.000000  2003.000000
max    404010.000000  3093.000000  2013.000000

In [65]:
data.describe(include='O')

name                       urlslug               ID  \
count                   6896                          6896             4883   
unique                  6896                          6896                3   
top     Batman (Bruce Wayne)  \/wiki\/Batman_(Bruce_Wayne)  Public Identity   
freq                       1                             1             2466   

                 ALIGN        EYE        HAIR              SEX  \
count             6295       3268        4622             6771   
unique               4         17          17                4   
top     Bad Characters  Blue Eyes  Black Hair  Male Characters   
freq              2895       1102        1574             4783   

                          GSM              ALIVE FIRST APPEARANCE  
count                      64               6893             6827  
unique                      2                  2              774  
top     Homosexual Characters  Living Characters   2010, December  
freq                       54               5200               78

checking null values

In [66]:
data.isnull().sum()/len(data)*100

page_id              0.000000
name                 0.000000
urlslug              0.000000
ID                  29.190835
ALIGN                8.715197
EYE                 52.610209
HAIR                32.975638
SEX                  1.812645
GSM                 99.071926
ALIVE                0.043503
APPEARANCES          5.147912
FIRST APPEARANCE     1.000580
YEAR                 1.000580
dtype: float64

In [67]:
data=data.drop(['GSM','YEAR','page_id','urlslug'],axis=1)

imputation 


In [68]:
!pip install feature-engine -q

In [69]:
import feature_engine

In [70]:
from feature_engine.imputation import MeanMedianImputer

In [71]:
a=MeanMedianImputer(imputation_method='median',
                           variables = ['APPEARANCES'])

In [72]:
data=a.fit_transform(data)

In [73]:
from feature_engine.imputation import CategoricalImputer

In [74]:
data.describe(include='O')

name               ID           ALIGN        EYE  \
count                   6896             4883            6295       3268   
unique                  6896                3               4         17   
top     Batman (Bruce Wayne)  Public Identity  Bad Characters  Blue Eyes   
freq                       1             2466            2895       1102   

              HAIR              SEX              ALIVE FIRST APPEARANCE  
count         4622             6771               6893             6827  
unique          17                4                  2              774  
top     Black Hair  Male Characters  Living Characters   2010, December  
freq          1574             4783               5200               78

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6896 entries, 0 to 6895
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              6896 non-null   object 
 1   ID                4883 non-null   object 
 2   ALIGN             6295 non-null   object 
 3   EYE               3268 non-null   object 
 4   HAIR              4622 non-null   object 
 5   SEX               6771 non-null   object 
 6   ALIVE             6893 non-null   object 
 7   APPEARANCES       6896 non-null   float64
 8   FIRST APPEARANCE  6827 non-null   object 
dtypes: float64(1), object(8)
memory usage: 485.0+ KB


In [76]:
aa= CategoricalImputer(imputation_method='frequent',
                           variables = ['ID','ALIGN','EYE','HAIR','SEX','ALIVE','FIRST APPEARANCE'])

In [77]:
data=aa.fit_transform(data)

In [78]:
data.isnull().sum()

name                0
ID                  0
ALIGN               0
EYE                 0
HAIR                0
SEX                 0
ALIVE               0
APPEARANCES         0
FIRST APPEARANCE    0
dtype: int64

In [79]:
import numpy as np

In [80]:
num=data.select_dtypes(include=[np.number])
num.skew()

APPEARANCES    16.229083
dtype: float64

In [81]:
from feature_engine.encoding import MeanEncoder
encoder=MeanEncoder(variables=['name','ID','EYE','HAIR','SEX','ALIVE','FIRST APPEARANCE'])

In [82]:
data=encoder.fit_transform(data,data['APPEARANCES'])

In [83]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['ALIGN'] = le.fit_transform(data['ALIGN'])

In [84]:
data.head()

name         ID  ALIGN        EYE       HAIR        SEX      ALIVE  \
0  3093.0  31.326827      1  19.851797  19.705561  23.148941  23.491639   
1  2496.0  31.326827      1  19.851797  19.705561  23.148941  23.491639   
2  1565.0  31.326827      1  29.328783  22.475610  23.148941  23.491639   
3  1316.0  18.129047      1  29.328783  27.078035  23.148941  23.491639   
4  1237.0  31.326827      1  19.851797  19.705561  23.148941  23.491639   

   APPEARANCES  FIRST APPEARANCE  
0       3093.0       3093.000000  
1       2496.0        290.000000  
2       1565.0        404.600000  
3       1316.0         92.793103  
4       1237.0        328.500000

In [85]:
op=data['ALIGN']
data=data.drop(['ALIGN'],axis=1)

In [86]:
data.head()

name         ID        EYE       HAIR        SEX      ALIVE  APPEARANCES  \
0  3093.0  31.326827  19.851797  19.705561  23.148941  23.491639       3093.0   
1  2496.0  31.326827  19.851797  19.705561  23.148941  23.491639       2496.0   
2  1565.0  31.326827  29.328783  22.475610  23.148941  23.491639       1565.0   
3  1316.0  18.129047  29.328783  27.078035  23.148941  23.491639       1316.0   
4  1237.0  31.326827  19.851797  19.705561  23.148941  23.491639       1237.0   

   FIRST APPEARANCE  
0       3093.000000  
1        290.000000  
2        404.600000  
3         92.793103  
4        328.500000

scaling


In [87]:
from sklearn.preprocessing import StandardScaler
b=StandardScaler()
data=b.fit_transform(data)
data=pd.DataFrame(data)

In [88]:
data.columns=['name','ID','EYE', 'HAIR', 'SEX',
       'ALIVE', 'APPEARANCES', 'FIRST APPEARANCE']

In [89]:
data.head()

name        ID       EYE      HAIR       SEX     ALIVE  APPEARANCES  \
0  36.043670  1.360117 -0.449681 -0.543951  0.497813  0.570429    36.043670   
1  29.035170  1.360117 -0.449681 -0.543951  0.497813  0.570429    29.035170   
2  18.105668  1.360117  1.037272 -0.043736  0.497813  0.570429    18.105668   
3  15.182525 -0.724967  1.037272  0.787369  0.497813  0.570429    15.182525   
4  14.255102  1.360117 -0.449681 -0.543951  0.497813  0.570429    14.255102   

   FIRST APPEARANCE  
0         56.680530  
1          4.934301  
2          7.049933  
3          1.293661  
4          5.645050

In [90]:
op.unique()

array([1, 0, 2, 3])

model building

In [91]:
x=data
y=op

In [92]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state =4)

xgboost classification

In [93]:
from xgboost import XGBClassifier
xgb_clf = XGBClassifier(maxdepth=5,learning_rate=1,n_estimators=1000)
xgb_clf.fit(x_train,y_train)

C:\Users\user\anaconda3\Lib\site-packages\xgboost\core.py:160: UserWarning: [18:41:02] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "maxdepth" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None, maxdepth=5,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=None,
              num_parallel_tree=None, ...)

In [94]:
y_train_pred = xgb_clf.predict(x_train)

In [95]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc_score = accuracy_score(y_train, y_train_pred)
print('Accuracy score :', acc_score)
pre_score = precision_score(y_train, y_train_pred, average='weighted')
print('Precision score :', pre_score)
re_call = recall_score(y_train, y_train_pred, average='weighted')
print('recall score :' ,re_call)
f1_score = f1_score(y_train, y_train_pred, average='weighted')
print('f1 score :',f1_score )
con_mat = confusion_matrix(y_train, y_train_pred)
print('confusion matrix :', con_mat)
cls_rep = classification_report(y_train, y_train_pred)
print('classification report :', cls_rep)

Accuracy score : 0.979076030660866
Precision score : 0.9790903621982636
recall score : 0.979076030660866
f1 score : 0.9790582579582744
confusion matrix : [[2399   35    3    0]
 [  40 1938    4    0]
 [  15    4  387    0]
 [   0    0    0    2]]
classification report :               precision    recall  f1-score   support

           0       0.98      0.98      0.98      2437
           1       0.98      0.98      0.98      1982
           2       0.98      0.95      0.97       406
           3       1.00      1.00      1.00         2

    accuracy                           0.98      4827
   macro avg       0.99      0.98      0.98      4827
weighted avg       0.98      0.98      0.98      4827



In [96]:
y_test_pred = xgb_clf.predict(x_test)

In [97]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc_score = accuracy_score(y_test, y_test_pred,)
print('Accuracy score :', acc_score)
pre_score = precision_score(y_test, y_test_pred, average='micro')
print('Precision score :', pre_score)
re_call = recall_score(y_test, y_test_pred, average='micro')
print('recall score :' ,re_call)
f1_score = f1_score(y_test, y_test_pred, average='micro')
print('f1 score :',f1_score )
con_mat = confusion_matrix(y_test, y_test_pred)
print('confusion matrix :', con_mat)
cls_rep = classification_report(y_test, y_test_pred)
print('classification report :', cls_rep)


Accuracy score : 0.5601739971000483
Precision score : 0.5601739971000483
recall score : 0.5601739971000483
f1 score : 0.5601739971000483
confusion matrix : [[672 344  43   0]
 [343 472  35   0]
 [ 68  76  15   0]
 [  1   0   0   0]]
classification report :               precision    recall  f1-score   support

           0       0.62      0.63      0.63      1059
           1       0.53      0.56      0.54       850
           2       0.16      0.09      0.12       159
           3       0.00      0.00      0.00         1

    accuracy                           0.56      2069
   macro avg       0.33      0.32      0.32      2069
weighted avg       0.55      0.56      0.55      2069



C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [98]:
# Apply L2 (Ridge) regularization

from xgboost import XGBClassifier

# Create an XGBoost classifier instance with regularization
xgb_clf_reg = XGBClassifier(max_depth=6, learning_rate=0.01, n_estimators=150, reg_alpha=5, reg_lambda=10)

# Train the regularized classifier on the training data
xgb_clf_reg.fit(x_train, y_train)
y_pred_l2 = xgb_clf_reg.predict(x_test)
accuracy_l2 = accuracy_score(y_test, y_pred_l2)
print("Accuracy with L2 (Ridge) regularization:", accuracy_l2)

Accuracy with L2 (Ridge) regularization: 0.6027066215563074


In [99]:
X=data
Y=op

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state =41,stratify=y)

svc 

In [101]:
from sklearn.svm import SVC
import numpy as np
svc_model = SVC(kernel='rbf',degree = 3, C=1.0, gamma='scale')
svc_model.fit(X_train,Y_train)

SVC()

In [102]:
Y_train_pred = svc_model.predict(X_train)

In [103]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc_score = accuracy_score(Y_train, Y_train_pred)
print('Accuracy score :', acc_score)
pre_score = precision_score(Y_train, Y_train_pred, average='weighted')
print('Precision score :', pre_score)
re_call = recall_score(Y_train, Y_train_pred, average='weighted')
print('recall score :' ,re_call)
f1_score = f1_score(Y_train, Y_train_pred, average='weighted')
print('f1 score :',f1_score )
con_mat = confusion_matrix(Y_train, Y_train_pred)
print('confusion matrix :', con_mat)
cls_rep = classification_report(Y_train, Y_train_pred)
print('classification report :', cls_rep)

Accuracy score : 0.5839376359680928
Precision score : 0.53188005278117
recall score : 0.5839376359680928
f1 score : 0.5502734481515341
confusion matrix : [[2170  626    0    0]
 [1214 1051    0    0]
 [ 247  205    0    0]
 [   0    3    0    0]]
classification report :               precision    recall  f1-score   support

           0       0.60      0.78      0.68      2796
           1       0.56      0.46      0.51      2265
           2       0.00      0.00      0.00       452
           3       0.00      0.00      0.00         3

    accuracy                           0.58      5516
   macro avg       0.29      0.31      0.30      5516
weighted avg       0.53      0.58      0.55      5516



C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\s

In [104]:
Y_test_pred = svc_model.predict(X_test)

In [105]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc_score = accuracy_score(Y_test, Y_test_pred)
print('Accuracy score :', acc_score)
pre_score = precision_score(Y_test, Y_test_pred, average='weighted')
print('Precision score :', pre_score)
re_call = recall_score(Y_test, Y_test_pred, average='weighted')
print('recall score :' ,re_call)
f1_score = f1_score(Y_test, Y_test_pred, average='weighted')
print('f1 score :',f1_score )
con_mat = confusion_matrix(Y_test, Y_test_pred)
print('confusion matrix :', con_mat)
cls_rep = classification_report(Y_test, Y_test_pred)
print('classification report :', cls_rep)

Accuracy score : 0.5717391304347826
Precision score : 0.5218477476336871
recall score : 0.5717391304347826
f1 score : 0.539380433203832
confusion matrix : [[529 171   0]
 [307 260   0]
 [ 72  41   0]]
classification report :               precision    recall  f1-score   support

           0       0.58      0.76      0.66       700
           1       0.55      0.46      0.50       567
           2       0.00      0.00      0.00       113

    accuracy                           0.57      1380
   macro avg       0.38      0.40      0.39      1380
weighted avg       0.52      0.57      0.54      1380



C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\s

logistic 

In [106]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(x_train,y_train)

LogisticRegression()

In [107]:
y_train_pred = log_reg.predict(x_train)

In [108]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc_score = accuracy_score(y_train, y_train_pred)
print('Accuracy score :', acc_score)
pre_score = precision_score(y_train, y_train_pred, average='weighted')
print('Precision score :', pre_score)
re_call = recall_score(y_train, y_train_pred, average='weighted')
print('recall score :' ,re_call)
f1_score = f1_score(y_train, y_train_pred, average='weighted')
print('f1 score :',f1_score )
con_mat = confusion_matrix(y_train, y_train_pred)
print('confusion matrix :', con_mat)
cls_rep = classification_report(y_train, y_train_pred)
print('classification report :', cls_rep)


Accuracy score : 0.562461155997514
Precision score : 0.5152808973502552
recall score : 0.562461155997514
f1 score : 0.5104671685944319
confusion matrix : [[2075  362    0    0]
 [1342  640    0    0]
 [ 274  132    0    0]
 [   1    1    0    0]]


C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


classification report :               precision    recall  f1-score   support

           0       0.56      0.85      0.68      2437
           1       0.56      0.32      0.41      1982
           2       0.00      0.00      0.00       406
           3       0.00      0.00      0.00         2

    accuracy                           0.56      4827
   macro avg       0.28      0.29      0.27      4827
weighted avg       0.52      0.56      0.51      4827



C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [109]:
y_test_pred = log_reg.predict(x_test)

In [110]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc_score = accuracy_score(y_test, y_test_pred)
print('Accuracy score :', acc_score)
pre_score = precision_score(y_test, y_test_pred, average='weighted')
print('Precision score :', pre_score)
re_call = recall_score(y_test, y_test_pred, average='weighted')
print('recall score :' ,re_call)
f1_score = f1_score(y_test, y_test_pred, average='weighted')
print('f1 score :',f1_score )
con_mat = confusion_matrix(y_test, y_test_pred)
print('confusion matrix :', con_mat)
cls_rep = classification_report(y_test, y_test_pred)
print('classification report :', cls_rep)

Accuracy score : 0.5654905751570807
Precision score : 0.5211992866168622
recall score : 0.5654905751570807
f1 score : 0.5161550707093675
confusion matrix : [[894 165   0   0]
 [574 276   0   0]
 [110  49   0   0]
 [  1   0   0   0]]
classification report :               precision    recall  f1-score   support

           0       0.57      0.84      0.68      1059
           1       0.56      0.32      0.41       850
           2       0.00      0.00      0.00       159
           3       0.00      0.00      0.00         1

    accuracy                           0.57      2069
   macro avg       0.28      0.29      0.27      2069
weighted avg       0.52      0.57      0.52      2069



C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\s

random forest

In [111]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier(n_estimators=10,random_state=0)
RFC.fit(x_train,y_train)

RandomForestClassifier(n_estimators=10, random_state=0)

In [112]:
y_train_pred = RFC.predict(x_train)

In [113]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc_score = accuracy_score(y_train, y_train_pred)
print('Accuracy score :', acc_score)
pre_score = precision_score(y_train, y_train_pred, average='weighted')
print('Precision score :', pre_score)
re_call = recall_score(y_train, y_train_pred, average='weighted')
print('recall score :' ,re_call)
f1_score = f1_score(y_train, y_train_pred, average='weighted')
print('f1 score :',f1_score )
con_mat = confusion_matrix(y_train, y_train_pred)
print('confusion matrix :', con_mat)
cls_rep = classification_report(y_train, y_train_pred)
print('classification report :', cls_rep)

Accuracy score : 0.9531800290035218
Precision score : 0.9536797654349282
recall score : 0.9531800290035218
f1 score : 0.9529516098597881
confusion matrix : [[2383   49    5    0]
 [ 116 1863    3    0]
 [  28   25  353    0]
 [   0    0    0    2]]
classification report :               precision    recall  f1-score   support

           0       0.94      0.98      0.96      2437
           1       0.96      0.94      0.95      1982
           2       0.98      0.87      0.92       406
           3       1.00      1.00      1.00         2

    accuracy                           0.95      4827
   macro avg       0.97      0.95      0.96      4827
weighted avg       0.95      0.95      0.95      4827



In [114]:
y_test_pred = RFC.predict(x_test)

In [115]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
acc_score = accuracy_score(y_test, y_test_pred)
print('Accuracy score :', acc_score)
pre_score = precision_score(y_test, y_test_pred, average='weighted')
print('Precision score :', pre_score)
re_call = recall_score(y_test, y_test_pred, average='weighted')
print('recall score :' ,re_call)
f1_score = f1_score(y_test, y_test_pred, average='weighted')
print('f1 score :',f1_score )
con_mat = confusion_matrix(y_test, y_test_pred)
print('confusion matrix :', con_mat)
cls_rep = classification_report(y_test, y_test_pred)
print('classification report :', cls_rep)

Accuracy score : 0.5693571773803769
Precision score : 0.5543704470608045
recall score : 0.5693571773803769
f1 score : 0.5611076858579587
confusion matrix : [[692 321  46   0]
 [342 473  35   0]
 [ 75  71  13   0]
 [  1   0   0   0]]
classification report :               precision    recall  f1-score   support

           0       0.62      0.65      0.64      1059
           1       0.55      0.56      0.55       850
           2       0.14      0.08      0.10       159
           3       0.00      0.00      0.00         1

    accuracy                           0.57      2069
   macro avg       0.33      0.32      0.32      2069
weighted avg       0.55      0.57      0.56      2069



C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda3\Lib\site-packages\s